//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIPER XCode Templates by Plyom
//

import UIKit

class ___FILEBASENAMEASIDENTIFIER___Manager
{
  
}
