//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIPER XCode Templates by Plyom
//

import UIKit

<<<<<<< HEAD
class ___FILEBASENAMEASIDENTIFIER___Interactor
{
    var output: ___FILEBASENAMEASIDENTIFIER___InteractorOutput
    
    init(output: ___FILEBASENAMEASIDENTIFIER___InteractorOutput) {
        self.output = output
    }
=======
class ___FILEBASENAMEASIDENTIFIER___Interactor: ___FILEBASENAMEASIDENTIFIER___InteractorInput
{
>>>>>>> 07c8dd4c4bf5a2f4e40ea1d4028e5610827df03c
    
    // MARK: Interactor Input

}
