//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIPER XCode Templates by Plyom
//
import UIKit

class ___FILEBASENAMEASIDENTIFIER___Presenter: ___FILEBASENAMEASIDENTIFIER___InteractorOutput
{
    
<<<<<<< HEAD
    var view: ___FILEBASENAMEASIDENTIFIER___ViewInterface
    
    init(view: ___FILEBASENAMEASIDENTIFIER___ViewInterface) {
        self.view = view
    }
    
=======
>>>>>>> 07c8dd4c4bf5a2f4e40ea1d4028e5610827df03c
    //MARK: Interface Module Methods
    
    //MARK: Interactor Output
    
}
